### ISSUE TITLE
Error trying to access APIKey request page

### ISSUE THREAD

**Issue by Damien2k9** [HugoDerave/ApexLegendsAPI#11]
Hi Hugo

I am trying to access the page to make the APIKey request and it is giving timeout. Is the page down?

`https://api.mozambiquehe.re/getkey`

Thanks

**Comment by HugoDerave** [comment]
Hey,
Yup our server is down, should be up very soon. Sorry!

**Comment by HugoDerave** [comment]
Fixed.

**Comment by Damien2k9** [comment]
Thanks
