### ISSUE TITLE
Only retrieving 'selected' legend instead of 'all' legends

### ISSUE THREAD

**Issue by AdrianDanlos** [HugoDerave/ApexLegendsAPI#12]
Hey! I have been playing around with your api for a couple of weeks and I haven't been able to figure out why in the legends section the api only finds the 'selected' legend object for some accounts instead of the default behaviour of retrieving 'all' & 'selected' legend objects.
 I hope you have a deeper insight than me about this issue.

Thx for the api!

**Comment by HugoDerave** [comment]
First query on a player only adds data to the "selected" object, and this data is saved in our database. The "all" object contains all the data we've saved in our database.

Can you give me player's example (name and platform) ?

**Comment by AdrianDanlos** [comment]
Ohhhh I get it that actually makes a lot of sense! 
Thank you for your reply!

**Comment by HugoDerave** [comment]
No problem :-)
