### ISSUE TITLE
Different values in 'all' and 'selected'

### ISSUE THREAD

**Issue by AdrianDanlos** [HugoDerave/ApexLegendsAPI#13]
I am not sure if the data I am retrieving is incorrect or maybe I am missing something. 
In the 'all' legends object Pathfinder does only have 35 kills. However in the 'selected' legend object it has 174 kills.

![image](https://user-images.githubusercontent.com/27602026/71414687-513ab180-2658-11ea-832d-f9cd1acf02c1.png)

**Comment by HugoDerave** [comment]
Can you give me the player name and platform ?

**Comment by AdrianDanlos** [comment]
Account: TheChineseSoul / Platform: PC
Account: AsiaTristanVigo / Platform: PC

**Comment by HugoDerave** [comment]
Fixed!
