### ISSUE TITLE
wrong GET arguments in Player statistics 

### ISSUE THREAD

**Issue by XuBin8866** [HugoDerave/ApexLegendsAPI#16]
HTTP Request in Player statistics shows 'https://api.mozambiquehe.re/bridge auth=YOUR_API_KEY&name=PLAYER_NAME&platform=PLATFORM' .actually the param is player instead of name.
query by uid has the same problem.
<img width="694" alt="image" src="https://user-images.githubusercontent.com/41318012/165912377-84c4f1ea-757b-4c12-931f-8f66b7743ca7.png">

**Comment by HugoDerave** [comment]
Fixed, ty for reporting
