### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by leanderlist** [HugoDerave/ApexLegendsAPI#19]
Hello, is this still maintained since the website is also down?

**Comment by boboshko** [comment]
I daresay not. I've been waiting for an answer to my questions for almost a month now.

**Comment by HugoDerave** [comment]
The API is still active, however this repo is no longer active/up to date with the API.

Please use https://apexlegendsapi.com for documentation needs & the associated discord server for support. (https://discord.gg/qd9cZQm)
