### ISSUE TITLE
It is not showing All champion stats

### ISSUE THREAD

**Issue by AxharKhan** [HugoDerave/ApexLegendsAPI#2]
I tried mine as well as for a friend of mine and only the selected legend details are shown.
He has 100+ kills on lifeline and other legends.

{
    "global": {
        "name": "OmgitsMarcusSs",
        "uid": 1002927795213,
        "platform": "PC",
        "level": 113,
        "toNextLevelPercent": 69,
        "internalUpdateCount": 3902,
        "battlepass": {
            "level": -1
        }
    },
    "realtime": {
        "lobbyState": "open",
        "isOnline": 0,
        "isInGame": 1,
        "canJoin": 0,
        "partyFull": 0,
        "selectedLegend": "Octane"
    },
    "legends": {
        "selected": {
            "Octane": {
                "kills": 0,
                "1905735931": 0
            }
        },
        "all": {
            "Octane": {
                "kills": "0"
            }
        }
    },
    "total": {
        "kills": 0,
        "kd": -1
    }
}

**Comment by AxharKhan** [comment]
It shows all the legends in version 2 but not the kills the kills are still 0. :(

**Comment by HugoDerave** [comment]
You have to loop through all your legends in game and make an API call each time.
Any new data will be added to the "all" field.

Sadly, we can't do more :/
