### ISSUE TITLE
[Feature request] Retrieving multiple profiles with one call

### ISSUE THREAD

**Issue by Mitcheljager** [HugoDerave/ApexLegendsAPI#3]
I would like to retrieve multiple (10+) profiles at once without having to make 10+ separate calls. I'm not certain how feasible this is with the current way of retrieving data from Respawn, but I've seen other APIs do similar things.

**Comment by HugoDerave** [comment]
Will work on it, should be added tonight or tomorrow :-)

**Comment by HugoDerave** [comment]
Hey, sorry for the delay. You can now search for multiple players by adding a coma between all players name. This would look like: (all players must be on the same platform)
http://api.mozambiquehe.re/bridge?platform=PC&player=PlayerA,PlayerB&auth=YOURAPIKEY&version=2

**Comment by Mitcheljager** [comment]
@HugoDerave Awesome, thank you very much!
