### ISSUE TITLE
[Feature Request] Finding players by their UID

### ISSUE THREAD

**Issue by Mitcheljager** [HugoDerave/ApexLegendsAPI#5]
I would like to be able to find players by their UID instead of their Username (and preferably without their Platform).

**Use case;**
We've got a system set up that automatically keeps tracks of a player's profile. We do this by storing their UID, Username, and Platform and making regular checks. We find them by their Username and Platform, but if they decide to change their Username this method will break.

Do you think this would be possible?

**Comment by HugoDerave** [comment]
Sure, should be added for tomorrow ! ;)

**Comment by HugoDerave** [comment]
Hey there,
Added the ability to make queries (single/multi) using player's UID. We still need the platform argument tho (might be changed in the future if really needed, but it needs a longer delay to implement it). Feel free to ask if you have any question!

(Doc updated in the repo)

**Comment by Mitcheljager** [comment]
@HugoDerave Thank you very much! Removing the platform was mostly just for ease of use, but I'm perfectly alright with still requiring it.
