### ISSUE TITLE
Need more Data

### ISSUE THREAD

**Issue by hadouken111** [HugoDerave/ApexLegendsAPI#6]
Hello, 
First nice work for this API, I have a question about the API, it's possible to have more data 
like : headshots, hstokills , daily_stats, smg kills, pistols kill etc..

**like this API** 
{"playerfound":true,"aid":"f5337d769b7b29628f59d8c84ea45d9d","name":"BallerInGame","platform":"PC","skillratio":1.8720000000000001083577672034152783453464508056640625,"visits":"8653","avatar":"https:\/\/apextab.com\/cache\/fc4c4cba183c2f81a94730be057cf07d.png","legend":"Wraith","level":"59","kills":"389","headshots":"568","hstokills":"0","matches":"333","damage":"0","lastdata":null,"kills_Bloodhound":"55","kills_Gibraltar":"10","kills_Lifeline":"14","kills_Pathfinder":"57","kills_Wraith":"13","kills_Bangalore":"227","kills_Caustic":"4","kills_Mirage":"9","headshots_Bloodhound":"89","headshots_Gibraltar":"12","headshots_Lifeline":"31","headshots_Pathfinder":"124","headshots_Wraith":"11","headshots_Bangalore":"283","headshots_Caustic":"6","headshots_Mirage":"12","matches_Bloodhound":"37","matches_Gibraltar":"16","matches_Lifeline":"14","matches_Pathfinder":"60","matches_Wraith":"20","matches_Bangalore":"167","matches_Caustic":"9","matches_Mirage":"10","damage_Bloodhound":"0","damage_Gibraltar":"0","damage_Lifeline":"0","damage_Pathfinder":"0","damage_Wraith":"0","damage_Bangalore":"0","damage_Caustic":"0","damage_Mirage":"0","globalrank":"97254","utime":"1556190269","kills_Octane":"0","headshots_Octane":"0","matches_Octane":"0","damage_Octane":"0","daily_stats":{"1555027200":{"kills":3,"headshots":2,"matches":2,"damage":0},"1553212800":{"kills":7,"headshots":6,"matches":4,"damage":0},"1552262400":{"kills":3,"headshots":9,"matches":5,"damage":0},"1552003200":{"kills":4,"headshots":4,"matches":2,"damage":0},"1551830400":{"kills":26,"headshots":24,"matches":15,"damage":0},"1551744000":{"kills":17,"headshots":33,"matches":8,"damage":0},"1551657600":{"kills":15,"headshots":19,"matches":14,"damage":0},"1551484800":{"kills":14,"headshots":20,"matches":8,"damage":0}}}

thank for your help

**Comment by HugoDerave** [comment]
Hey, this is working as intended. You have to show the trackers you want to get data from while being ingame, and only those will be registered. Once we have them, their data will still be displayed even if they aren't showed. You also have to loop through all the wanted legends, and do an API call each time.

If you need more help, feel free to respond ;)

**Comment by hadouken111** [comment]
Bonsoir, merci pour votre réponse, désolé mon anglais n'est pas très bon je ne sais pas si du coup ma question à bien été interpelé, avant de trouvé votre api j'ai consulté de nombreuse autres malheureusement elles ne fonctionne pas vraiment car les données son fausse, ma question est la suivante pensez-vous faire évoluer l'API afin d'obtenir des données supplémentaires telle que : headshots, smg kills, pistols kill et avoir les stats du jour "kills":3,"headshots":2,"matches":2,"damage":0
Je me doute que cela est possible étant donnée que les autres API le font.
Dans l'attente d'une réponse 
Merci

**Comment by HugoDerave** [comment]
Alors on va faire ça en français, ça sera plus simple!

C'est déjà implanté dans l'API, il suffit d'avoir ces bannières affichées sur son joueur (comme les autres API). Une fois que ces données ont été affichées pour la première fois, elles seront sauvegardées et affichées au prochain appel de l'API (Il faut bien sûr faire un appel sur l'API entre chaque changement de légende/bannières afin de sauvegarder les nouvelles données)

**Comment by HugoDerave** [comment]
L'exemple est visible, par exemple, avec la requête sur le joueur "HeyImLIFELINE" sur "PC" ;)
