### ISSUE TITLE
Can't fetch news API

### ISSUE THREAD

**Issue by CloudPower97** [HugoDerave/ApexLegendsAPI#7]
Hey there,
I'm facing a strange issue,
I can correctly fetch the _stats_ `API` using my key, but I can't do the same for the _news_ `API`, it always responds with
`Error: API key doesn't exist !`
I've tried with both `auth` `GET` parameter and `Authorization` `header`.

Am I missing something?

**Comment by HugoDerave** [comment]
It's working on my side. 
Can you PM me on discord your API key?

**Comment by CloudPower97** [comment]
@HugoDerave Sure, can you give me your username/identifier?

**Comment by HugoDerave** [comment]
hugo#5020 (there is our discord server link on the desc page ;p)

**Comment by CloudPower97** [comment]
@HugoDerave Yes, you are right. I've sent you a friend request BTW :smile:

**Comment by HugoDerave** [comment]
### **Fixed**
