### ISSUE TITLE
Unable to fetch data

### ISSUE THREAD

**Issue by deepakkaku** [HugoDerave/ApexLegendsAPI#8]
The APi is not responding to requests anymore.
I also tried creating a new API key but its no longer working.

I get the following error

api.mozambiquehe.re is currently unable to handle this request.
HTTP ERROR 500

**Comment by HugoDerave** [comment]
This has been fixed 1h30 ago - thx for the report!

**Comment by deepakkaku** [comment]
Thank you very much. I look forward to more stats being added
